import os
import csv

os.makedirs("data", exist_ok=True)

products = [
    {
        "product_id": 1,
        "product_name": "Lenovo IdeaPad Laptop",
        "category": "Bilgisayar",
        "brand": "Lenovo",
        "price": 18500,
        "cash_price": 17900,
        "bank_transfer_price": 17650,
        "card_price": 18500,
        "installment_3_total": 19050,
        "installment_6_total": 19750,
        "installment_9_total": 20700,
        "senet_total_price": 22500,
        "senet_monthly_9": 2500,
        "color": "Gri",
        "processor": "Intel Core i5",
        "ram": "8 GB",
        "storage": "512 GB SSD",
        "screen_size": "15.6 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Öğrenci, günlük kullanım, ofis",
        "features": "Hafif yapı, SSD depolama, uygun fiyat, öğrenci dostu",
        "description": "Öğrenci ve günlük kullanım için uygun fiyat performans laptop",
        "product_link": "https://nevade.com/product/1",
        "image_link": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 2,
        "product_name": "HP Gaming Laptop",
        "category": "Bilgisayar",
        "brand": "HP",
        "price": 42000,
        "cash_price": 40700,
        "bank_transfer_price": 40200,
        "card_price": 42000,
        "installment_3_total": 43200,
        "installment_6_total": 44900,
        "installment_9_total": 47200,
        "senet_total_price": 51200,
        "senet_monthly_9": 5689,
        "color": "Siyah",
        "processor": "Intel Core i7",
        "ram": "16 GB",
        "storage": "1 TB SSD",
        "screen_size": "15.6 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Oyun, yüksek performans, tasarım",
        "features": "Güçlü ekran kartı, yüksek RAM, performans odaklı",
        "description": "Oyun ve yüksek performans için güçlü ekran kartlı laptop",
        "product_link": "https://nevade.com/product/2",
        "image_link": "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 3,
        "product_name": "Apple MacBook Air M2",
        "category": "Bilgisayar",
        "brand": "Apple",
        "price": 52900,
        "cash_price": 51500,
        "bank_transfer_price": 50900,
        "card_price": 52900,
        "installment_3_total": 54500,
        "installment_6_total": 56800,
        "installment_9_total": 59900,
        "senet_total_price": 65800,
        "senet_monthly_9": 7311,
        "color": "Uzay Grisi",
        "processor": "Apple M2",
        "ram": "8 GB",
        "storage": "256 GB SSD",
        "screen_size": "13.6 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Premium kullanım, okul, ofis, taşınabilirlik",
        "features": "Uzun pil ömrü, hafif tasarım, premium ekosistem",
        "description": "Taşınabilir premium laptop ve uzun pil ömrü isteyen kullanıcılar için uygun",
        "product_link": "https://nevade.com/product/3",
        "image_link": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 4,
        "product_name": "Asus VivoBook Laptop",
        "category": "Bilgisayar",
        "brand": "Asus",
        "price": 24500,
        "cash_price": 23800,
        "bank_transfer_price": 23500,
        "card_price": 24500,
        "installment_3_total": 25200,
        "installment_6_total": 26300,
        "installment_9_total": 27600,
        "senet_total_price": 30900,
        "senet_monthly_9": 3433,
        "color": "Gümüş",
        "processor": "AMD Ryzen 5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "screen_size": "15.6 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Öğrenci, ofis, günlük kullanım",
        "features": "16 GB RAM, uygun fiyat, güçlü günlük performans",
        "description": "Günlük kullanım ve ofis işleri için fiyat performans laptop",
        "product_link": "https://nevade.com/product/4",
        "image_link": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 5,
        "product_name": "Samsung Galaxy Telefon",
        "category": "Telefon",
        "brand": "Samsung",
        "price": 29500,
        "cash_price": 28700,
        "bank_transfer_price": 28350,
        "card_price": 29500,
        "installment_3_total": 30400,
        "installment_6_total": 31700,
        "installment_9_total": 33500,
        "senet_total_price": 37200,
        "senet_monthly_9": 4133,
        "color": "Siyah",
        "processor": "Exynos",
        "ram": "8 GB",
        "storage": "256 GB",
        "screen_size": "6.6 inç",
        "energy_class": "",
        "capacity": "5000 mAh batarya",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Günlük kullanım, kamera, sosyal medya",
        "features": "Yüksek batarya, geniş ekran, Android ekosistem",
        "description": "30 bin TL altı günlük kullanım için uygun akıllı telefon",
        "product_link": "https://nevade.com/product/5",
        "image_link": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 6,
        "product_name": "Apple iPhone 15",
        "category": "Telefon",
        "brand": "Apple",
        "price": 68500,
        "cash_price": 66700,
        "bank_transfer_price": 65900,
        "card_price": 68500,
        "installment_3_total": 70600,
        "installment_6_total": 73500,
        "installment_9_total": 77200,
        "senet_total_price": 85500,
        "senet_monthly_9": 9500,
        "color": "Mavi",
        "processor": "Apple A16",
        "ram": "6 GB",
        "storage": "128 GB",
        "screen_size": "6.1 inç",
        "energy_class": "",
        "capacity": "3349 mAh batarya",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Premium telefon, kamera, uzun vadeli kullanım",
        "features": "iOS ekosistemi, güçlü kamera, premium deneyim",
        "description": "Yüksek performanslı premium akıllı telefon",
        "product_link": "https://nevade.com/product/6",
        "image_link": "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 7,
        "product_name": "Beko Buzdolabı",
        "category": "Beyaz Eşya",
        "brand": "Beko",
        "price": 24000,
        "cash_price": 23200,
        "bank_transfer_price": 22900,
        "card_price": 24000,
        "installment_3_total": 24800,
        "installment_6_total": 25900,
        "installment_9_total": 27400,
        "senet_total_price": 30500,
        "senet_monthly_9": 3389,
        "color": "Beyaz",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A+",
        "capacity": "514 L",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Aile kullanımı, çeyiz, günlük ev kullanımı",
        "features": "Geniş hacim, enerji tasarrufu, uygun fiyat",
        "description": "Geniş hacimli aile kullanımı için uygun buzdolabı",
        "product_link": "https://nevade.com/product/7",
        "image_link": "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 8,
        "product_name": "Arçelik Buzdolabı",
        "category": "Beyaz Eşya",
        "brand": "Arçelik",
        "price": 36500,
        "cash_price": 35200,
        "bank_transfer_price": 34800,
        "card_price": 36500,
        "installment_3_total": 37700,
        "installment_6_total": 39200,
        "installment_9_total": 41500,
        "senet_total_price": 46200,
        "senet_monthly_9": 5133,
        "color": "İnox",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A++",
        "capacity": "560 L",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Çeyiz, aile kullanımı, enerji tasarrufu",
        "features": "A++ enerji sınıfı, geniş iç hacim, inox tasarım",
        "description": "Enerji tasarruflu geniş iç hacimli buzdolabı",
        "product_link": "https://nevade.com/product/8",
        "image_link": "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 9,
        "product_name": "Siemens Buzdolabı",
        "category": "Beyaz Eşya",
        "brand": "Siemens",
        "price": 48900,
        "cash_price": 47400,
        "bank_transfer_price": 46900,
        "card_price": 48900,
        "installment_3_total": 50500,
        "installment_6_total": 52800,
        "installment_9_total": 55900,
        "senet_total_price": 62500,
        "senet_monthly_9": 6944,
        "color": "İnox",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A+++",
        "capacity": "580 L",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Premium beyaz eşya, aile, uzun vadeli kullanım",
        "features": "A+++ enerji sınıfı, sessiz çalışma, geniş hacim",
        "description": "Premium segment sessiz çalışan geniş hacimli buzdolabı",
        "product_link": "https://nevade.com/product/9",
        "image_link": "https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 10,
        "product_name": "Arçelik Çamaşır Makinesi",
        "category": "Beyaz Eşya",
        "brand": "Arçelik",
        "price": 21000,
        "cash_price": 20400,
        "bank_transfer_price": 20100,
        "card_price": 21000,
        "installment_3_total": 21600,
        "installment_6_total": 22600,
        "installment_9_total": 23900,
        "senet_total_price": 26800,
        "senet_monthly_9": 2978,
        "color": "Beyaz",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A++",
        "capacity": "9 kg",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Çeyiz, aile, günlük ev kullanımı",
        "features": "9 kg kapasite, enerji tasarrufu, sessiz çalışma",
        "description": "Enerji tasarruflu ve geniş kapasiteli çamaşır makinesi",
        "product_link": "https://nevade.com/product/10",
        "image_link": "https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 11,
        "product_name": "Dyson Dikey Süpürge",
        "category": "Ev Elektroniği",
        "brand": "Dyson",
        "price": 28500,
        "cash_price": 27600,
        "bank_transfer_price": 27200,
        "card_price": 28500,
        "installment_3_total": 29400,
        "installment_6_total": 30700,
        "installment_9_total": 32600,
        "senet_total_price": 36200,
        "senet_monthly_9": 4022,
        "color": "Mor",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "",
        "capacity": "60 dk çalışma süresi",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Premium temizlik, pratik kullanım",
        "features": "Kablosuz kullanım, güçlü çekim, hafif gövde",
        "description": "Kablosuz güçlü çekim performansı sunan premium dikey süpürge",
        "product_link": "https://nevade.com/product/11",
        "image_link": "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 12,
        "product_name": "Philips Süpürge",
        "category": "Ev Elektroniği",
        "brand": "Philips",
        "price": 7200,
        "cash_price": 6950,
        "bank_transfer_price": 6800,
        "card_price": 7200,
        "installment_3_total": 7450,
        "installment_6_total": 7850,
        "installment_9_total": 8300,
        "senet_total_price": 9600,
        "senet_monthly_9": 1067,
        "color": "Siyah",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "",
        "capacity": "2 L toz haznesi",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Ekonomik temizlik, günlük ev kullanımı",
        "features": "Güçlü emiş, uygun fiyat, kablolu kullanım",
        "description": "Ev temizliği için güçlü emiş gücüne sahip elektrikli süpürge",
        "product_link": "https://nevade.com/product/12",
        "image_link": "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 13,
        "product_name": "Samsung 4K Televizyon",
        "category": "Televizyon",
        "brand": "Samsung",
        "price": 32500,
        "cash_price": 31500,
        "bank_transfer_price": 30900,
        "card_price": 32500,
        "installment_3_total": 33500,
        "installment_6_total": 35100,
        "installment_9_total": 37200,
        "senet_total_price": 41500,
        "senet_monthly_9": 4611,
        "color": "Siyah",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "55 inç",
        "energy_class": "A",
        "capacity": "4K UHD",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Salon, film, günlük TV kullanımı",
        "features": "4K görüntü, akıllı TV, geniş ekran",
        "description": "4K görüntü kalitesi sunan akıllı televizyon",
        "product_link": "https://nevade.com/product/13",
        "image_link": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=80"
    },
    {
        "product_id": 14,
        "product_name": "LG OLED Televizyon",
        "category": "Televizyon",
        "brand": "LG",
        "price": 58900,
        "cash_price": 57200,
        "bank_transfer_price": 56500,
        "card_price": 58900,
        "installment_3_total": 60800,
        "installment_6_total": 63500,
        "installment_9_total": 67200,
        "senet_total_price": 74500,
        "senet_monthly_9": 8278,
        "color": "Siyah",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "55 inç",
        "energy_class": "A",
        "capacity": "OLED 4K",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Kredi kartı, havale, peşin, senet",
        "use_case": "Premium sinema deneyimi, oyun, film",
        "features": "OLED panel, yüksek kontrast, premium görüntü",
        "description": "Premium görüntü kalitesi isteyen kullanıcılar için OLED televizyon",
        "product_link": "https://nevade.com/product/14",
        "image_link": "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=900&q=80"
    }
]

fieldnames = list(products[0].keys())

with open("data/products.csv", "w", newline="", encoding="utf-8-sig") as file:
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(products)

print("Gelişmiş products.csv oluşturuldu: data/products.csv")
print(f"Ürün sayısı: {len(products)}")
print("Yeni kolonlar:")
for column in fieldnames:
    print("-", column)