import os
import pandas as pd

os.makedirs("data", exist_ok=True)

products = [
    # =========================
    # BİLGİSAYAR / LAPTOP
    # =========================
    {
        "product_id": 1,
        "product_name": "Lenovo IdeaPad 3 Laptop",
        "category": "Bilgisayar",
        "brand": "Lenovo",
        "price": 18500,
        "cash_price": 18000,
        "bank_transfer_price": 17650,
        "card_price": 18500,
        "installment_3_total": 18500,
        "installment_6_total": 18500,
        "installment_9_total": 19800,
        "senet_total_price": 22500,
        "senet_monthly_9": 2500,
        "color": "Gri",
        "processor": "Intel Core i5",
        "ram": "8 GB",
        "storage": "512 GB SSD",
        "screen_size": "15.6 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, 3 taksit, 6 taksit, 9 taksit, senet",
        "use_case": "Öğrenci, okul, günlük kullanım, ofis",
        "features": "Taşınabilir, uygun fiyatlı, SSD depolama, günlük kullanım için yeterli performans",
        "description": "Öğrenci ve günlük kullanım için uygun fiyatlı Lenovo laptop.",
        "product_link": "https://www.nevade.com/lenovo-ideapad-3",
        "image_link": ""
    },
    {
        "product_id": 2,
        "product_name": "HP Pavilion Laptop",
        "category": "Bilgisayar",
        "brand": "HP",
        "price": 24500,
        "cash_price": 23800,
        "bank_transfer_price": 23200,
        "card_price": 24500,
        "installment_3_total": 24500,
        "installment_6_total": 24500,
        "installment_9_total": 26200,
        "senet_total_price": 29500,
        "senet_monthly_9": 3278,
        "color": "Gümüş",
        "processor": "Intel Core i5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "screen_size": "15.6 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Öğrenci, ofis, yazılım, günlük kullanım",
        "features": "16 GB RAM, hızlı SSD, ofis ve okul için güçlü performans",
        "description": "Ders, ofis ve günlük kullanım için dengeli performans sunan HP laptop.",
        "product_link": "https://www.nevade.com/hp-pavilion-laptop",
        "image_link": ""
    },
    {
        "product_id": 3,
        "product_name": "Apple MacBook Air M2",
        "category": "Bilgisayar",
        "brand": "Apple",
        "price": 42900,
        "cash_price": 41900,
        "bank_transfer_price": 41000,
        "card_price": 42900,
        "installment_3_total": 42900,
        "installment_6_total": 42900,
        "installment_9_total": 45900,
        "senet_total_price": 50500,
        "senet_monthly_9": 5611,
        "color": "Uzay Grisi",
        "processor": "Apple M2",
        "ram": "8 GB",
        "storage": "256 GB SSD",
        "screen_size": "13.6 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Öğrenci, ofis, tasarım, taşınabilir kullanım",
        "features": "Hafif, uzun pil ömrü, güçlü M2 işlemci, premium kullanım",
        "description": "Taşınabilirlik ve uzun pil ömrü isteyen öğrenciler ve profesyoneller için MacBook Air.",
        "product_link": "https://www.nevade.com/macbook-air-m2",
        "image_link": ""
    },
    {
        "product_id": 4,
        "product_name": "Asus VivoBook 15 Laptop",
        "category": "Bilgisayar",
        "brand": "Asus",
        "price": 21900,
        "cash_price": 21300,
        "bank_transfer_price": 20800,
        "card_price": 21900,
        "installment_3_total": 21900,
        "installment_6_total": 21900,
        "installment_9_total": 23500,
        "senet_total_price": 26800,
        "senet_monthly_9": 2978,
        "color": "Mavi",
        "processor": "AMD Ryzen 5",
        "ram": "8 GB",
        "storage": "512 GB SSD",
        "screen_size": "15.6 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Öğrenci, ofis, günlük kullanım",
        "features": "Ryzen işlemci, SSD, uygun fiyatlı, taşınabilir",
        "description": "Okul ve ofis işleri için fiyat performans odaklı Asus laptop.",
        "product_link": "https://www.nevade.com/asus-vivobook-15",
        "image_link": ""
    },
    {
        "product_id": 5,
        "product_name": "HP Victus Gaming Laptop",
        "category": "Bilgisayar",
        "brand": "HP",
        "price": 38900,
        "cash_price": 37900,
        "bank_transfer_price": 36900,
        "card_price": 38900,
        "installment_3_total": 38900,
        "installment_6_total": 38900,
        "installment_9_total": 41900,
        "senet_total_price": 46500,
        "senet_monthly_9": 5167,
        "color": "Siyah",
        "processor": "Intel Core i7",
        "ram": "16 GB",
        "storage": "1 TB SSD",
        "screen_size": "16.1 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Oyun, yazılım, performans, tasarım",
        "features": "Güçlü işlemci, 16 GB RAM, 1 TB SSD, yüksek performans",
        "description": "Oyun ve performans isteyen kullanıcılar için güçlü HP Victus laptop.",
        "product_link": "https://www.nevade.com/hp-victus-gaming",
        "image_link": ""
    },

    # =========================
    # TELEFON
    # =========================
    {
        "product_id": 6,
        "product_name": "Samsung Galaxy A55 Telefon",
        "category": "Telefon",
        "brand": "Samsung",
        "price": 18900,
        "cash_price": 18400,
        "bank_transfer_price": 17900,
        "card_price": 18900,
        "installment_3_total": 18900,
        "installment_6_total": 18900,
        "installment_9_total": 20200,
        "senet_total_price": 22800,
        "senet_monthly_9": 2533,
        "color": "Lacivert",
        "processor": "Exynos",
        "ram": "8 GB",
        "storage": "256 GB",
        "screen_size": "6.6 inç",
        "energy_class": "",
        "capacity": "5000 mAh",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Günlük kullanım, fotoğraf, sosyal medya",
        "features": "Geniş ekran, iyi kamera, güçlü batarya",
        "description": "Günlük kullanım ve kamera performansı için dengeli Samsung telefon.",
        "product_link": "https://www.nevade.com/samsung-galaxy-a55",
        "image_link": ""
    },
    {
        "product_id": 7,
        "product_name": "Apple iPhone 15",
        "category": "Telefon",
        "brand": "Apple",
        "price": 52900,
        "cash_price": 51500,
        "bank_transfer_price": 50500,
        "card_price": 52900,
        "installment_3_total": 52900,
        "installment_6_total": 52900,
        "installment_9_total": 56500,
        "senet_total_price": 62500,
        "senet_monthly_9": 6944,
        "color": "Siyah",
        "processor": "A16 Bionic",
        "ram": "",
        "storage": "128 GB",
        "screen_size": "6.1 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Premium telefon, kamera, günlük kullanım, Apple ekosistemi",
        "features": "iOS, güçlü kamera, uzun kullanım ömrü, premium deneyim",
        "description": "Apple ekosistemi ve güçlü kamera isteyen kullanıcılar için iPhone 15.",
        "product_link": "https://www.nevade.com/iphone-15",
        "image_link": ""
    },
    {
        "product_id": 8,
        "product_name": "Xiaomi Redmi Note 13",
        "category": "Telefon",
        "brand": "Xiaomi",
        "price": 12900,
        "cash_price": 12500,
        "bank_transfer_price": 12100,
        "card_price": 12900,
        "installment_3_total": 12900,
        "installment_6_total": 12900,
        "installment_9_total": 13900,
        "senet_total_price": 15800,
        "senet_monthly_9": 1756,
        "color": "Yeşil",
        "processor": "Snapdragon",
        "ram": "8 GB",
        "storage": "256 GB",
        "screen_size": "6.67 inç",
        "energy_class": "",
        "capacity": "5000 mAh",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Uygun fiyatlı telefon, günlük kullanım, sosyal medya",
        "features": "Büyük ekran, yüksek depolama, uygun fiyat",
        "description": "Bütçe dostu ve yüksek depolamalı Xiaomi telefon.",
        "product_link": "https://www.nevade.com/xiaomi-redmi-note-13",
        "image_link": ""
    },
    {
        "product_id": 9,
        "product_name": "Apple iPhone 13",
        "category": "Telefon",
        "brand": "Apple",
        "price": 34900,
        "cash_price": 33900,
        "bank_transfer_price": 33200,
        "card_price": 34900,
        "installment_3_total": 34900,
        "installment_6_total": 34900,
        "installment_9_total": 37400,
        "senet_total_price": 41800,
        "senet_monthly_9": 4644,
        "color": "Mavi",
        "processor": "A15 Bionic",
        "ram": "",
        "storage": "128 GB",
        "screen_size": "6.1 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Apple telefon, günlük kullanım, kamera, uygun fiyatlı iPhone",
        "features": "iOS, güçlü kamera, 128 GB depolama, iPhone 15'e göre daha uygun fiyat",
        "description": "Apple ekosistemine daha uygun fiyatla girmek isteyen kullanıcılar için iPhone 13.",
        "product_link": "https://www.nevade.com/iphone-13",
        "image_link": ""
    },
    {
        "product_id": 10,
        "product_name": "Apple iPhone 14",
        "category": "Telefon",
        "brand": "Apple",
        "price": 42900,
        "cash_price": 41900,
        "bank_transfer_price": 41000,
        "card_price": 42900,
        "installment_3_total": 42900,
        "installment_6_total": 42900,
        "installment_9_total": 45900,
        "senet_total_price": 50800,
        "senet_monthly_9": 5644,
        "color": "Mor",
        "processor": "A15 Bionic",
        "ram": "",
        "storage": "128 GB",
        "screen_size": "6.1 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Apple telefon, kamera, günlük kullanım, uzun ömürlü telefon",
        "features": "iOS, güçlü kamera, 128 GB depolama, iPhone 15'e yakın deneyim",
        "description": "iPhone 15'e göre daha uygun fiyatlı ama güçlü Apple telefon alternatifi.",
        "product_link": "https://www.nevade.com/iphone-14",
        "image_link": ""
    },
    {
        "product_id": 11,
        "product_name": "Apple iPhone 15 Pro",
        "category": "Telefon",
        "brand": "Apple",
        "price": 68900,
        "cash_price": 67500,
        "bank_transfer_price": 66000,
        "card_price": 68900,
        "installment_3_total": 68900,
        "installment_6_total": 68900,
        "installment_9_total": 73800,
        "senet_total_price": 81500,
        "senet_monthly_9": 9056,
        "color": "Titanyum",
        "processor": "A17 Pro",
        "ram": "",
        "storage": "256 GB",
        "screen_size": "6.1 inç",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Premium Apple telefon, kamera, performans, profesyonel kullanım",
        "features": "A17 Pro işlemci, 256 GB depolama, güçlü kamera, premium Apple deneyimi",
        "description": "Yüksek performans ve premium kamera isteyen kullanıcılar için iPhone 15 Pro.",
        "product_link": "https://www.nevade.com/iphone-15-pro",
        "image_link": ""
    },

    # =========================
    # BUZDOLABI
    # =========================
    {
        "product_id": 12,
        "product_name": "Beko Buzdolabı",
        "category": "Beyaz Eşya",
        "brand": "Beko",
        "price": 24000,
        "cash_price": 23500,
        "bank_transfer_price": 22900,
        "card_price": 24000,
        "installment_3_total": 24000,
        "installment_6_total": 24000,
        "installment_9_total": 25800,
        "senet_total_price": 30500,
        "senet_monthly_9": 3389,
        "color": "Beyaz",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A+",
        "capacity": "514 L",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Aile, günlük kullanım, uygun fiyatlı beyaz eşya",
        "features": "Geniş iç hacim, uygun fiyat, temel aile kullanımı",
        "description": "Uygun fiyatlı ve aile kullanımı için yeterli kapasiteye sahip Beko buzdolabı.",
        "product_link": "https://www.nevade.com/beko-buzdolabi",
        "image_link": ""
    },
    {
        "product_id": 13,
        "product_name": "Arçelik Buzdolabı",
        "category": "Beyaz Eşya",
        "brand": "Arçelik",
        "price": 36500,
        "cash_price": 35500,
        "bank_transfer_price": 34800,
        "card_price": 36500,
        "installment_3_total": 36500,
        "installment_6_total": 36500,
        "installment_9_total": 38900,
        "senet_total_price": 43800,
        "senet_monthly_9": 4867,
        "color": "Inox",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A++",
        "capacity": "560 L",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Aile, çeyiz, uzun vadeli kullanım",
        "features": "Daha yüksek kapasite, enerji tasarrufu, inox tasarım, geniş iç hacim",
        "description": "Çeyiz ve uzun vadeli aile kullanımı için güçlü Arçelik buzdolabı.",
        "product_link": "https://www.nevade.com/arcelik-buzdolabi",
        "image_link": ""
    },
    {
        "product_id": 14,
        "product_name": "Siemens Buzdolabı",
        "category": "Beyaz Eşya",
        "brand": "Siemens",
        "price": 48900,
        "cash_price": 47500,
        "bank_transfer_price": 46500,
        "card_price": 48900,
        "installment_3_total": 48900,
        "installment_6_total": 48900,
        "installment_9_total": 52500,
        "senet_total_price": 58500,
        "senet_monthly_9": 6500,
        "color": "Inox",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A+++",
        "capacity": "580 L",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Premium aile kullanımı, enerji tasarrufu, geniş kapasite",
        "features": "Yüksek enerji verimliliği, premium tasarım, geniş hacim",
        "description": "Enerji verimliliği ve premium kullanım isteyen aileler için Siemens buzdolabı.",
        "product_link": "https://www.nevade.com/siemens-buzdolabi",
        "image_link": ""
    },
    {
        "product_id": 15,
        "product_name": "Bosch Buzdolabı",
        "category": "Beyaz Eşya",
        "brand": "Bosch",
        "price": 41500,
        "cash_price": 40500,
        "bank_transfer_price": 39800,
        "card_price": 41500,
        "installment_3_total": 41500,
        "installment_6_total": 41500,
        "installment_9_total": 44500,
        "senet_total_price": 49800,
        "senet_monthly_9": 5533,
        "color": "Beyaz",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A++",
        "capacity": "570 L",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Aile, geniş hacim, enerji tasarrufu",
        "features": "Geniş kapasite, sessiz çalışma, enerji verimliliği",
        "description": "Aile kullanımı için geniş hacimli ve enerji tasarruflu Bosch buzdolabı.",
        "product_link": "https://www.nevade.com/bosch-buzdolabi",
        "image_link": ""
    },

    # =========================
    # ÇAMAŞIR MAKİNESİ
    # =========================
    {
        "product_id": 16,
        "product_name": "Beko Çamaşır Makinesi",
        "category": "Beyaz Eşya",
        "brand": "Beko",
        "price": 17500,
        "cash_price": 17000,
        "bank_transfer_price": 16500,
        "card_price": 17500,
        "installment_3_total": 17500,
        "installment_6_total": 17500,
        "installment_9_total": 18800,
        "senet_total_price": 21900,
        "senet_monthly_9": 2433,
        "color": "Beyaz",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A+",
        "capacity": "8 kg",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Uygun fiyatlı, küçük aile, günlük kullanım",
        "features": "8 kg kapasite, ekonomik fiyat, temel yıkama programları",
        "description": "Uygun fiyatlı çamaşır makinesi arayan kullanıcılar için Beko modeli.",
        "product_link": "https://www.nevade.com/beko-camasir-makinesi",
        "image_link": ""
    },
    {
        "product_id": 17,
        "product_name": "Arçelik Çamaşır Makinesi",
        "category": "Beyaz Eşya",
        "brand": "Arçelik",
        "price": 21000,
        "cash_price": 20500,
        "bank_transfer_price": 19900,
        "card_price": 21000,
        "installment_3_total": 21000,
        "installment_6_total": 21000,
        "installment_9_total": 22600,
        "senet_total_price": 26800,
        "senet_monthly_9": 2978,
        "color": "Beyaz",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A++",
        "capacity": "9 kg",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Aile, çeyiz, günlük kullanım",
        "features": "9 kg kapasite, enerji tasarrufu, hızlı yıkama",
        "description": "Aile ve çeyiz kullanımı için uygun Arçelik çamaşır makinesi.",
        "product_link": "https://www.nevade.com/arcelik-camasir-makinesi",
        "image_link": ""
    },
    {
        "product_id": 18,
        "product_name": "Siemens Çamaşır Makinesi",
        "category": "Beyaz Eşya",
        "brand": "Siemens",
        "price": 32900,
        "cash_price": 31900,
        "bank_transfer_price": 31200,
        "card_price": 32900,
        "installment_3_total": 32900,
        "installment_6_total": 32900,
        "installment_9_total": 35200,
        "senet_total_price": 39800,
        "senet_monthly_9": 4422,
        "color": "Beyaz",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "A+++",
        "capacity": "10 kg",
        "warranty": "3 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Premium aile kullanımı, geniş kapasite",
        "features": "10 kg kapasite, sessiz motor, enerji tasarrufu, hassas yıkama",
        "description": "Geniş aileler için yüksek kapasiteli Siemens çamaşır makinesi.",
        "product_link": "https://www.nevade.com/siemens-camasir-makinesi",
        "image_link": ""
    },

    # =========================
    # EV ELEKTRONİĞİ
    # =========================
    {
        "product_id": 19,
        "product_name": "Dyson Dikey Süpürge",
        "category": "Ev Elektroniği",
        "brand": "Dyson",
        "price": 22900,
        "cash_price": 22300,
        "bank_transfer_price": 21800,
        "card_price": 22900,
        "installment_3_total": 22900,
        "installment_6_total": 22900,
        "installment_9_total": 24600,
        "senet_total_price": 27800,
        "senet_monthly_9": 3089,
        "color": "Gri",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Ev temizliği, pratik kullanım, güçlü çekim",
        "features": "Kablosuz kullanım, güçlü çekim, hafif tasarım, pratik temizlik",
        "description": "Pratik ve güçlü temizlik isteyen kullanıcılar için Dyson dikey süpürge.",
        "product_link": "https://www.nevade.com/dyson-dikey-supurge",
        "image_link": ""
    },
    {
        "product_id": 20,
        "product_name": "Philips Süpürge",
        "category": "Ev Elektroniği",
        "brand": "Philips",
        "price": 8900,
        "cash_price": 8600,
        "bank_transfer_price": 8350,
        "card_price": 8900,
        "installment_3_total": 8900,
        "installment_6_total": 8900,
        "installment_9_total": 9600,
        "senet_total_price": 11200,
        "senet_monthly_9": 1244,
        "color": "Siyah",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "",
        "capacity": "3 L",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Uygun fiyatlı ev temizliği",
        "features": "Toz torbalı kullanım, ekonomik fiyat, güçlü motor",
        "description": "Uygun fiyatlı ve temel ev temizliği için Philips süpürge.",
        "product_link": "https://www.nevade.com/philips-supurge",
        "image_link": ""
    },
    {
        "product_id": 21,
        "product_name": "Tefal Airfryer",
        "category": "Ev Elektroniği",
        "brand": "Tefal",
        "price": 6500,
        "cash_price": 6300,
        "bank_transfer_price": 6100,
        "card_price": 6500,
        "installment_3_total": 6500,
        "installment_6_total": 6500,
        "installment_9_total": 7000,
        "senet_total_price": 8200,
        "senet_monthly_9": 911,
        "color": "Siyah",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "",
        "capacity": "4.2 L",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Mutfak, pratik yemek, az yağlı pişirme",
        "features": "Az yağlı pişirme, kompakt tasarım, kolay temizlik",
        "description": "Pratik ve az yağlı pişirme için Tefal airfryer.",
        "product_link": "https://www.nevade.com/tefal-airfryer",
        "image_link": ""
    },
    {
        "product_id": 22,
        "product_name": "Karaca Kahve Makinesi",
        "category": "Ev Elektroniği",
        "brand": "Karaca",
        "price": 4200,
        "cash_price": 4050,
        "bank_transfer_price": 3900,
        "card_price": 4200,
        "installment_3_total": 4200,
        "installment_6_total": 4200,
        "installment_9_total": 4550,
        "senet_total_price": 5300,
        "senet_monthly_9": 589,
        "color": "Krem",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "",
        "energy_class": "",
        "capacity": "4 fincan",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Mutfak, kahve, çeyiz",
        "features": "Türk kahvesi, otomatik pişirme, kompakt tasarım",
        "description": "Çeyiz ve günlük kahve kullanımı için Karaca kahve makinesi.",
        "product_link": "https://www.nevade.com/karaca-kahve-makinesi",
        "image_link": ""
    },

    # =========================
    # TELEVİZYON
    # =========================
    {
        "product_id": 23,
        "product_name": "Samsung 4K Televizyon",
        "category": "Televizyon",
        "brand": "Samsung",
        "price": 28900,
        "cash_price": 28000,
        "bank_transfer_price": 27400,
        "card_price": 28900,
        "installment_3_total": 28900,
        "installment_6_total": 28900,
        "installment_9_total": 30900,
        "senet_total_price": 34800,
        "senet_monthly_9": 3867,
        "color": "Siyah",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "55 inç",
        "energy_class": "A",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Salon, film, günlük TV kullanımı",
        "features": "4K çözünürlük, akıllı TV, geniş ekran",
        "description": "Salon ve film deneyimi için 55 inç Samsung 4K televizyon.",
        "product_link": "https://www.nevade.com/samsung-4k-tv",
        "image_link": ""
    },
    {
        "product_id": 24,
        "product_name": "LG OLED Televizyon",
        "category": "Televizyon",
        "brand": "LG",
        "price": 56900,
        "cash_price": 55500,
        "bank_transfer_price": 54000,
        "card_price": 56900,
        "installment_3_total": 56900,
        "installment_6_total": 56900,
        "installment_9_total": 61000,
        "senet_total_price": 68200,
        "senet_monthly_9": 7578,
        "color": "Siyah",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "65 inç",
        "energy_class": "A",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Premium salon, sinema, oyun",
        "features": "OLED panel, yüksek görüntü kalitesi, 65 inç geniş ekran",
        "description": "Premium görüntü kalitesi isteyen kullanıcılar için LG OLED televizyon.",
        "product_link": "https://www.nevade.com/lg-oled-tv",
        "image_link": ""
    },
    {
        "product_id": 25,
        "product_name": "TCL Akıllı TV",
        "category": "Televizyon",
        "brand": "TCL",
        "price": 17900,
        "cash_price": 17400,
        "bank_transfer_price": 16900,
        "card_price": 17900,
        "installment_3_total": 17900,
        "installment_6_total": 17900,
        "installment_9_total": 19200,
        "senet_total_price": 21800,
        "senet_monthly_9": 2422,
        "color": "Siyah",
        "processor": "",
        "ram": "",
        "storage": "",
        "screen_size": "50 inç",
        "energy_class": "A",
        "capacity": "",
        "warranty": "2 yıl",
        "stock_status": "Stokta",
        "installment_available": "Evet",
        "payment_options": "Peşin, havale, kart, taksit, senet",
        "use_case": "Uygun fiyatlı salon TV, günlük kullanım",
        "features": "Akıllı TV, 4K, uygun fiyat, geniş ekran",
        "description": "Uygun fiyatlı akıllı televizyon isteyen kullanıcılar için TCL TV.",
        "product_link": "https://www.nevade.com/tcl-akilli-tv",
        "image_link": ""
    }
]

df = pd.DataFrame(products)
df.to_csv("data/products.csv", index=False, encoding="utf-8-sig")

print("data/products.csv oluşturuldu.")
print(f"Toplam ürün sayısı: {len(df)}")